# Generated by Django 5.2.6 on 2025-09-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(choices=[('BASIC', 'BASIC'), ('STANDARD', 'STANDARD'), ('PREMIUM', 'PREMIUM')], max_length=16)),
                ('count_basic', models.IntegerField(blank=True, null=True)),
                ('count_standard', models.IntegerField(blank=True, null=True)),
                ('count_premium', models.IntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
