# Generated by Django 5.2.5 on 2025-09-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_telemetryevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('wifi_connected', models.BooleanField(default=False)),
                ('rtc_available', models.BooleanField(default=False)),
                ('sd_card_available', models.BooleanField(default=False)),
                ('current_count_basic', models.IntegerField(default=0)),
                ('current_count_standard', models.IntegerField(default=0)),
                ('current_count_premium', models.IntegerField(default=0)),
                ('uptime_seconds', models.IntegerField(blank=True, null=True)),
                ('device_timestamp', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='device_timestamp',
            field=models.CharField(blank=True, help_text='Timestamp from ESP32 device', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='wifi_status',
            field=models.BooleanField(blank=True, help_text='WiFi connection status', null=True),
        ),
        migrations.AlterField(
            model_name='telemetryevent',
            name='event_type',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('STANDARD', 'STANDARD'), ('PREMIUM', 'PREMIUM'), ('status', 'Status Update')], max_length=16),
        ),
        migrations.CreateModel(
            name='UsageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('date', models.DateField(db_index=True)),
                ('basic_count', models.IntegerField(default=0)),
                ('standard_count', models.IntegerField(default=0)),
                ('premium_count', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('first_event', models.DateTimeField(blank=True, null=True)),
                ('last_event', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', '-device_id'],
                'unique_together': {('device_id', 'date')},
            },
        ),
    ]
