# Generated by Django 5.2.5 on 2025-09-11 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_outlet_machine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['outlet__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='machine',
            name='device_id',
        ),
        migrations.CreateModel(
            name='MachineDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('deactivated_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='telemetry.machine')),
            ],
            options={
                'ordering': ['-is_active', '-assigned_date'],
                'unique_together': {('machine', 'device_id')},
            },
        ),
    ]
